<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
      
        <?php echo $this->headTitle(); ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        //->prependStylesheet($this->basePath() . '/js/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.min.css')
        				->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/js/jquery-ui-1.10.3/themes/base/jquery-ui.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ?>
        <script>var basePatch  = '<?=$this->basePath()?>'</script>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/usuario.js')
                                      ->prependFile($this->basePath() . '/js/publico.js')
                                      ->prependFile($this->basePath() . '/js/jquery.maskedinput.min.js')
                                      //->prependFile($this->basePath() . '/js/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery-ui-1.10.3/ui/jquery-ui.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>


    <!--[if IE 9]>
      <link href="<?=$this->basePath()?>/css/style-ie.css" rel="stylesheet" type="text/css">      
    <![endif]-->


    <!--[if !IE]><!--><script>
    if (/*@cc_on!@*/false) {
        document.documentElement.className+='ie10';
    }
    </script><!--<![endif]-->

    </head>
    <body>

        <div id="header">
         
      </div>
        
     
      <!--LOGIN -->

         <div id="Login_Cadastro" style="display:none">
          <div id="BoxLoginCadastro">
            <div id="btn_form">
               <a href="" class="status_entrar status_entrar_active" alt="login" title="Login">entrar</a>
               <a href="" class="status_criar_conta" alt="Criar conta" title="Criar conta">criar conta</a>
               <a href="" class="status_fechar"alt="fechar" title="Fechar">fechar</a>
           </div>
           <div id="form_login">     
              <form action="" class="formActionLogin">
                   <label class="status_login">Login:</label><br/><input type="text" class="login" value="Digite seu Login"><br/>
                   <label class="status_password">Senha:</label><br/><input type="password" class="Password" value="criar senha"><br/>
                   <a href="" class="esqueceuSenha">Esqueceu sua senha?</a><br/>
                   <input type="submit" value="Entrar" class="Eventlogin"><br/><br/><br/>
              </form>
           </div>

          <div id="form_cadastro" style="display:none">
             <form action="" class="formActionCadastro">
                  <label class="status_email">*Digite aqui o seu e-mail:</label><br/><input type="text" class="email" value=""><br/>
                  <label class="status_login">*Criar nome de usuário:</label><br/><input type="text" class="login" value=""><br/>
                  <label class="status_password">*Senha:</label><br/><input type="password" class="Password" ><br/>
                  <label class="status_password">*Confirmar senha:</label><br/>
                  <input type="password" class="PasswordConfirm" ><br/><br/>
                 <input type="submit" value="cadastrar" class="Eventcadastrar"><br/><br/><br/>
            </form>
         </div>
       </div>
      </div>


       <!--ERRO-->

        <!--ERRO-->
        <div id="form_erro" style="display:none">
          <div id="BoxFormErro">
                <div class="modelNotificacao">
                   <p class="atencaoErro"><!-- Titulo Box --></p>
                   <p class="erro"><!-- Lista de mensagens --></p>
                   <span class="tipo_erro"></span>
                   <br/>
                   <a href="" class="tentarNovamente"><!-- Titulo Botão --></a>
                </div> 
          </div>
        </div>

        
          <!--*****************************CONTEUDO*****************************-->



<div id="geral">

 <!--*****************************CONTEUDO TOPO*****************************-->
  <div id="topo_menu">
    <div id="menu_central">
      <a href="<?=$this->basePath()?>" title="SELETO ALIMENTOS"><h1 class="logo_seleto" title="Seleto Alimentos" style="background: url(<?=$this->basePath()?>/images/open-source-logo.png) no-repeat;">SELETO ALIMENTOS</h1></a>
            
          <div id="box_menu" style="margin-top:50px;">
            <img class="phone"src="<?=$this->basePath()?>/images/phone.png">
            <p class="txt_phone">Televendas: 55 11 3611-3143 / 3611-3179</p>
            <form action="<?php echo $this->url('publico-busca-produto'); ?>" method="get">            
                <input placeholder="buscar produto" class="search_topo" id="search" name="p">
                <input type="submit" value="Pesquisar" class="lupa_topo">
            </form>

          </div>
    </div>

  </div>

 <!--*****************************FIM DO CONTEUDO TOPO*****************************-->



	<!--****************BANNER PAGAMENTO/ENTREGAS/REDES SOCIAIS****************-->
                <div id="banner_informativo">
                	<div id="box_banner_informativo">
                	 <div id="ContenTopoHeader">
            <div id="mn_topo">
                  <ul class="mn_topo">
                    <li class="Menu_topo">
                      Bem vindo à nossa loja online
                      </li>
                      <li class="Menu_topo">
                      <a href="#" class="eventOpenPopUp">Faça login ou cadastre-se</a>
                      </li>
                      <li class="Menu_topo">
                      <a href="#" class="eventOpenPopUp">Acompanhe seus pedidos</a>
                    </li>
                     <li class="Menu_topo" style="background:none;">
                      <a href="<?=$this->url("publico-duvidas")?>">Dúvidas frequentes</a></li>
                  </ul>
             </div>


              <a href="#" class="actionOpenCarrinho">
                <span class="Cesta" title="Minha Cesta"><br/>
                    
                  <div id="Box_Visor_Qtd" style="<?if(count($this->carrinhoLista['listaAtual']) != 0) print "display:block"; else print "display:none";?>">  
                    <span class="Visor_Qtd"><?if(count($this->carrinhoLista['listaAtual']) != 0) print count($this->carrinhoLista['listaAtual']);?></span>
                  </div>
					<?
						if($this->carrinhoLista['listaAtual'])
						{
					?>
                  <p class="mc">MINHA CESTA</p>
                   <p class="valor_total"><?=$this->carrinhoLista['valorTotal']?></p>
                    <img class="dt_cesta" src="<?=$this->basePath()?>/images/dt_cesta.png">
						<?
						}
						else
						{
						
						?>
						<p class="mc">MINHA CESTA</p>
						<p class="valor_total"><?=$this->carrinhoLista['valorTotal']?></p>
					 <img class="dt_cesta" src="<?=$this->basePath()?>/images/dt_cesta.png">	
						<?
						}
						?>
                </span>
              </a>
           </div>

              <div id="BoxCestaForm">    
                <div id="box_compras" style="display:none;">
                  <?
                    print  $this->partial("layout/carrinho",array("carrinhoLista" => $this->carrinhoLista));
                  ?>                
                </div>
              </div>
                   </div>
                </div>
    <!--****************FIM DO BANNER PAGAMENTO/ENTREGAS/REDES SOCIAIS****************-->

<!--*****************************CAMINHO SITE***************************-->
                	 <?
                    print  $this->partial("layout/caminho",array("caminhoDefines" => $this->caminhoDefines));
                  ?>

<!--***************************** FIM DO CAMINHO SITE***************************-->
                	

<div id="conteudo_principal">

                <!--MENU LATERAL-->
                <script>
                $(document).ready(function(){
                	$("#accordian h3").click(function(){
                		//slide up all the link lists
                		$("#accordian ul ul").slideUp();
                		//slide down the link list below the h3 clicked - only if its closed
                		if(!$(this).next().is(":visible"))
                		{
                			$(this).next().slideDown();
                		}
                	})
                })
                </script>
                
<style>
#accordian {
	background: #004050;
	width: 140px;
	margin-right:15px;
	float:left;
	color: white;
	/*Some cool shadow and glow effect*/
	box-shadow: 
		0 5px 15px 1px rgba(0, 0, 0, 0.6), 
		0 0 200px 1px rgba(255, 255, 255, 0.5);
}
/*heading styles*/
#accordian h3 {
	font-size: 12px;
	line-height: 34px;
	padding: 0 10px;
	cursor: pointer;
	/*fallback for browsers not supporting gradients*/
	background: #003040; 
	background: linear-gradient(#003040, #002535);
}
/*heading hover effect*/
#accordian h3:hover {
	text-shadow: 0 0 1px rgba(255, 255, 255, 0.7);
}
/*iconfont styles*/
#accordian h3 span {
	font-size: 16px;
	margin-right: 10px;
}
/*list items*/
#accordian li {
	list-style-type: none;
}
/*links*/
#accordian ul ul li a {
	color: white;
	text-decoration: none;
	font-size: 11px;
	line-height: 27px;
	display: block;
	padding: 0 15px;
	/*transition for smooth hover animation*/
	transition: all 0.15s;
}
/*hover effect on links*/
#accordian ul ul li a:hover {
	background: #003545;
	border-left: 5px solid lightgreen;
}
/*Lets hide the non active LIs by default*/
#accordian ul ul {
	display: none;
}
#accordian li.active ul {
	display: block;
}
              </style>
<!-- prefix free to deal with vendor prefixes -->
<script src="http://thecodeplayer.com/uploads/js/prefixfree-1.0.7.js" type="text/javascript" type="text/javascript"></script>
               
                <?php 
                
                    if($this->matchedRoute != "publico-carrinho-compra" && $this->matchedRoute != "publico-finaliza-compra" && $this->matchedRoute != "publico-duvidas")
                    {
                ?>
                  <div id="accordian">
	<ul>
	<?php
                        $a = 1;
                        foreach($this->categorias as $categoria): 
						?> 
		<li class="active">
			<h3><span class="icon-dashboard"></span><?php echo $categoria->getNome(); ?></h3>
			<ul>
			<?php
                                    $i = 1; 
                                    foreach($categoria->getSubcategorias() as $subcategoria): 
                                        if(count($subcategoria->getProdutos()) > 0): 
                                    ?>
				<li><a href="<?php echo $this->url('publico-categoria/publico-categoria-e-subcategoria', array('categoriaslug'=>$categoria->getSlug(), 'subcategoriaslugSub'=>$subcategoria->getSlugSubcategoria())); ?>"><?php echo $subcategoria->getNome(); ?></a></li>
				<?php $i--; endif; endforeach; ?>  
			</ul>
		</li> 
		<?php $a--; endforeach; ?>
		
		<!-- we will keep this LI open by default -->
		
	</ul>
</div>
                  <?php 
                    }
                  ?>
                <!--*********************FIM DO MENU LATERAL*********************-->
                
        <?php echo $this->content; ?>
        
                <!--*********************FIM DO MENU LATERAL PUBLICIDADE********************-->

          </div>

</div>

        
       <!--*******************FOOTER************************-->

<div id="footer">

    <div id="box_search_footer">
        <div class="search_footer">
            <form action="<?php echo $this->url('publico-busca-produto'); ?>" method="get">
              <input placeholder="buscar produto" class="search_footer" id="search_footer" name="p">
              <input type="submit" value="pesquisar" class="lupa_footer" title="Buscar Produto">
            </form>
        </div>
    </div>

    <div id="box_newsletter_footer">
      <div class="newsletter_footer">
           <p class="newsletter_footer">RECEBA DESCONTOS E OFERTAS EXCLUSIVAS</p>
           <input placeholder="Digite seu nome" class="news_footer"/>
           <input placeholder="Digite seu e-mail" class="news_footer"/>
           <input type="submit" class="ok_footer" value="OK" title="Receba descontos e ofertas exclusivas"/>
        </div>
    </div>

    <div id="box_menu_footer">
      <div class="menu_footer">
          <ul class="mn_footer">
             <li>institucional</li>
                 <ul class="submenu">
                    <li><a href="<?=$this->url("publico-duvidas")?>#duvida1" title="Quem Somos" dir="#duvida1">Quem Somos</a></li>
                    <li><a href="<?=$this->url("publico-duvidas")?>#duvida2" title="Mapa do Site" dir="#duvida2">Mapa do Site</a></li>
                    <li><a href="<?=$this->url("publico-duvidas")?>#duvida6" title="Fale Conosco" dir="#duvida6">Fale Conosco</a></li>
                 </ul>
          </ul>

        <ul class="mn_footer">
          <li>dúvidas frequentes</li>
            <ul class="submenu">
               <li><a href="<?=$this->url("publico-duvidas")?>#duvida3" title="Termos de Pesquisa" dir="#duvida3">Perguntas Frequentes</a></li>
               <li><a href="" title="Faça login ou cadastre-se" class="eventOpenPopUp">Faça login ou cadastre-se</a></li>
               <li><a href="" title="Meus Pedidos" class="eventOpenPopUp">Meus Pedidos</a></li>
                <li><a href="<?=$this->url("publico-duvidas")?>#duvida5" title="Política de Privacidade" dir="#duvida5">Política de Privacidade</a></li>
            </ul>
        </ul>

        <ul class="mn_footer">
          <li>entregas</li>
          
          <img src="<?=$this->basePath()?>/images/icon_sedex.png" alt="e-Sedex" title="Entrega via e-Sedex" class="icon_e-sedex"/>
           <p class="text_entregas">As entregas serão<br/> feitas via e-Sedex</p>     
        </ul>

        <ul class="mn_footer">
          <li>redes sociais</li>
            <ul class="submenu">  
              <p class="text_redes_sociais">Acompanhe o Café Seleto <br/> nas redes sociais:</p>      
      <li class="redeSociais"><a href="https://www.facebook.com/SeletoAlimentos?ref=ts&fref=ts" target="_blank" class="redes_sociais"><img src="<?=$this->basePath()?>/images/facebook.png" alt="facebook" title="Facebook"/></a></li>
     <li class="redeSociais"><a href="https://twitter.com/seletoalimentos" target="_blank" class="redes_sociais"><img src="<?=$this->basePath()?>/images/twitter.png" alt="twitter" title="Twitter"/></a></li>
     <li class="redeSociais"><a href="http://instagram.com/seletoalimentos#" target="_blank" class="redes_sociais"><img src="<?=$this->basePath()?>/images/instagran.png" alt="instagran" title="Instagran"/></a></li>
            </ul>
        </ul>

      </div>
    </div>

    <div id="box_pagamento_footer">
      <div class="pagamento_footer">
          <p class="pagamentos">Formas de pagamento:</p>
          <a href=""><img src="<?=$this->basePath()?>/images/pagseguro.png" alt="Faça seu pagamento pelo PagSeguro" title="Faça seu pagamento pelo PagSeguro" /></a>
       </div>

    </div>

    <div id="box_direitosReservados_footer">
      <div class="direitosReservados_footer">
          <p class="direitos_reservados">© 2013 seleto. Todos os Direitos Reservados.</p>
        </div>
    </div>

</div>

<!--************************FIM DO FOOTER****************************-->
        

    </body>
</html>
        