<div class="breadcrumbs">
    <ul>
                    <li class="home">
                            <a href="http://web-experiment.info/magento14/bluescale/" title="Go to Home Page">Home</a>
                                        <span>/ </span>
                        </li>
                    <li class="category163">
                            <a href="http://web-experiment.info/magento14/bluescale/apparel.html" title="">Apparel</a>
                                        <span>/ </span>
                        </li>
                    <li class="category125">
                            <strong>Kids &amp; Baby</strong>
                                    </li>
            </ul>
</div>