<?php 
$filter = new \NumberFormatter('pt_BR', \NumberFormatter::CURRENCY);
?>
<div class="cart">
    <div class="page-title title-buttons">
        <h1>Carrinho de Compras</h1>
                <ul class="checkout-types">
            <li>
    <a href="<?=$this->url("publico-finaliza-compra")?>"><button type="button" title="Proceed to Checkout" class="button btn-checkout"><span><span>Finalizar Compra</span></span></button></a>
</li>
        </ul>
            </div>
    <ul class="messages"><li class="success-msg"><ul><li>Aqui você encontra todas informações de sua compra.</li></ul></li></ul>        <form action="http://web-experiment.info/magento14/bluescale/checkout/cart/updatePost/" method="post">
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">
                <colgroup><col width="1">
                <col width="1">
                <col>
                                        <col width="1">
                                        <col width="1">
                            <col width="1">
                        
                            </colgroup><thead>
                    <tr class="first last">
                        <th rowspan="1" class="a-center">&nbsp;</th>
                        <th rowspan="1">&nbsp;</th>
                        <th rowspan="1"><span class="nobr">Product Name</span></th>
                                                <th class="a-center" colspan="1"><span class="nobr">Valor unitário</span></th>
                        <th rowspan="1" class="a-center">Quant.</th>
                        <th class="a-center" colspan="1">Subtotal</th>
                    </tr>
                                    </thead>
                <tfoot>
                    <tr class="first last">
                        <td colspan="50" class="a-right last">
                                                            <button type="button" title="Continue Shopping" class="button btn-continue" onclick="setLocation('http://web-experiment.info/magento14/bluescale/')"><span><span>Volte a comprar</span></span></button>
                                                        <button type="submit" title="Update Shopping Cart" class="button btn-update"><span><span>Atualizar Carrinho</span></span></button>
                        </td>
                    </tr>
                </tfoot>
                <tbody>
                 <?php 
    foreach($this->carrinhoLista['listaAtual'] AS $produto)
    {
    	?>
                                    <tr class="first last odd">
    <td class="a-center"><a href="http://web-experiment.info/magento14/bluescale/checkout/cart/delete/id/84041/uenc/aHR0cDovL3dlYi1leHBlcmltZW50LmluZm8vbWFnZW50bzE0L2JsdWVzY2FsZS9jaGVja291dC9jYXJ0L2luZGV4Lz9fX19TSUQ9VQ,,/" title="Remove item" class="btn-remove2">Remove item</a></td>
    <td><a href="http://web-experiment.info/magento14/bluescale/recycled-paper-pocket-journals-spring.html" title="Good Tote Bag"><img src="<?=$this->basePath()?>/images/produtos/thumb_small/<?=$produto['produto']->getFoto();?>" width="75" height="75" alt="Good Tote Bag"></a></td>
    <td>
        <h2 class="product-name">
                    <a href="http://web-experiment.info/magento14/bluescale/recycled-paper-pocket-journals-spring.html">Good Tote Bag</a>
                </h2>
                    </td>
            <td class="a-right">
                    <span class="cart-price">
        
                            <span class="price"><?=$produto['produto']->getValor(true)?></span>            
        </span>


            </td>
            <td class="a-center">
        <input name="cart[84041][qty]" value="<?
			            				  if($produto['produto']->getEstoque()[0]->getQuantidade() < $produto['quantidade'])
			            				  {
			            				  	  print $produto['produto']->getEstoque()[0]->getQuantidade();
			            				  }
			            				  else
			            				  {
			            				     print $produto['quantidade'];
			            				  }
			            				  ?>" size="4" title="Qty" class="input-text qty" maxlength="12">
    </td>
        <td class="a-right last">
                    <span class="cart-price">
        
                            <span class="price"><?=$filter->formatCurrency($produto['produto']->getValor()*$produto['quantidade'], 'BRL');?></span>            
        </span>
            </td>
        </tr>
        <?php 
    } 
        ?>
                                </tbody>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </fieldset>
    </form>
    <div class="cart-collaterals">
        <div class="col2-set">
            <div class="col-1">
                            </div>
            <div class="col-2">
                <form id="discount-coupon-form" action="http://web-experiment.info/magento14/bluescale/checkout/cart/couponPost/" method="post">
   
</form>

            </div>
        </div>
        <ul id="HeaderCestaCompras">
							  <li class="txt_prazoDentrega">Consulte o valor do seu frete</li>
								 <li class="SeuCep">
								 	<p class="txt_SeuCep">Digite seu CEP</p>

								 	    <a href="#" title="Calcular frete">
									 		
									 		<input class="DigCep1" value="<?if(!empty($this->cep)) print $this->cep?>">
									 		<span class="CalcFret">
									 		 Calcular frete
									 		</span>

									 	</a>
								 </li>

								 <li>
								 	<a target="_blank" class="ProcurarCep" href="http://www.buscacep.correios.com.br/" title="Encontre seu CEP">
								 		Não sei meu CEP
								 	</a>
								 </li>
						</ul>
						<ul id="BoxListaProduto">
						 <span class="BoxEntrega">						 	
						 	 <p class="TxtBoxEntrega">
						 		<span class="CaixaAltaEntrega">Prazo máximo de entrega:</span>
						 		 até 7 dias úteis</p>
						 </span>
							<li class="ListaDaCesta2">								
								<p class="txt_aviso"><span class="txt_aviso_atencao">Atenção:</span> O prazo começa a contar a<br/> partir da aprovação do crédito.</p>
		                        <p class="txt_frete"><?if(!empty($this->valorFrete)) print "FRETE: ".$this->valorFrete;?></p>
		                        
		                        <p class="CalcSomaValor"><?=$this->carrinhoLista['valorTotal']?></p>
		                        <p class="txt_TotalFrete">Total<?if(!empty($this->valorFrete)) print " com frete";?>:</p>
							</li>

						</ul>
    </div>
</div>